apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbGN4aWZjay5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiZG1WdWEyRjBPbFJsYzNSQU1USXoiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
 
